spring:
  web:
    resources:
      static-locations: classpath:/static/
  mail:
    # 发送者邮箱
    username: 2065343055@qq.com
    #申请到的授权码
    password: unxxwgdgibgjcebc
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    port: 465
    protocol: smtps
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
          debug: true
          ssl: true

uploadFile:
    maxSize: 10
    path: C:/Users/23756/IdeaProjects/CampusTaskPlatform/target/classes/static/upload/

